version: "3.5"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moskow
      - AUTO_UPDATE=true #optional
    ports:
      - 9117:9117

